Add Task2.1
Parean/Homeworks pull request #27
Opened 2016-12-14 10:46 UTC by Parean

2016-12-23 06:46 UTC, jzuken requested changes

2016-12-23 06:46 UTC, jzuken commented on 3/Hw2/Task2.1/networktester.h
> +    void correctOrderOfInfection()
ну ок, а как проверить правильность порядка в большой сложной сети с разными компьютерами?

2016-12-29 07:24 UTC, Parean commented on 3/Hw2/Task2.1/networktester.h
> +    void correctOrderOfInfection()
@jzuken 
Этот тест и проверяет
Сеть сама генерирует рандомные компьютеры
Тест работает на сети заданного размера, можно выбрать size большим числом

2016-12-29 08:16 UTC, jzuken commented on 3/Hw2/Task2.1/networktester.h
> +    void correctOrderOfInfection()
я хочу понять, как проверить алгоритм заражения с учётом рандомности процесса

2017-02-11 12:42 UTC, merged