Task4.1
Parean/Homeworks pull request #29
Opened 2016-12-29 00:37 UTC by Parean

2016-12-29 07:10 UTC, jzuken requested changes

2016-12-29 07:10 UTC, jzuken commented on 3/Hw4/Task4_1/client.h
> +#include "networkelement.h"
нет такого файла в репозитории

2016-12-29 07:35 UTC, jzuken commented
1. хочется различать игроков на экране
2. хочется, чтобы по нажатию на "start server" что-то всё же происходило
3. хочется рисовать область поражения снарядом
4. хочется иметь возможность менять тип снаряда (отображая текущий)

2017-02-01 14:26 UTC, Parean commented
Смена снаряда на tab

2017-02-11 12:39 UTC, merged